// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi55DVoavaeoNG0rVKO0j3TLhsbPYzzK0',
    appId: '1:740966990243:web:e559154fdf8644d249da16',
    messagingSenderId: '740966990243',
    projectId: 'flutter-application-1-50c80',
    authDomain: 'flutter-application-1-50c80.firebaseapp.com',
    storageBucket: 'flutter-application-1-50c80.appspot.com',
    measurementId: 'G-VE2ZJ86FGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCymbW7djRo4Ssxomh0Jt5Tn0LzWrSC6L0',
    appId: '1:740966990243:android:7c1d698d6508869a49da16',
    messagingSenderId: '740966990243',
    projectId: 'flutter-application-1-50c80',
    storageBucket: 'flutter-application-1-50c80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtKQ7cyEEnyGgoPL5EbstHKKQQ-w6Mes',
    appId: '1:740966990243:ios:81b53a8b05e6f6d349da16',
    messagingSenderId: '740966990243',
    projectId: 'flutter-application-1-50c80',
    storageBucket: 'flutter-application-1-50c80.appspot.com',
    iosClientId:
        '740966990243-6jitr920ai5sq0i3d243iddc8d9hefk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtKQ7cyEEnyGgoPL5EbstHKKQQ-w6Mes',
    appId: '1:740966990243:ios:81b53a8b05e6f6d349da16',
    messagingSenderId: '740966990243',
    projectId: 'flutter-application-1-50c80',
    storageBucket: 'flutter-application-1-50c80.appspot.com',
    iosClientId:
        '740966990243-6jitr920ai5sq0i3d243iddc8d9hefk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
